# Generated by Django 5.1.1 on 2024-10-14 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzterketarenAplikazioa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='zita_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
